[build]
  command = "yarn install && yarn prisma generate && yarn build"
  publish = ".next"

[environment]
  DATABASE_URL = "mongodb+srv://prismaNext:i9FVbYnjlFKgtpnK@prisma-next.qqjt5xi.mongodb.net/todonext"
