[build]
  command = "yarn install && yarn prisma generate && yarn build"
  publish = ".next"

[environment]
  DATABASE_URL = "mongodb+srv://prismaNext:i9FVbYnjlFKgtpnK@prisma-next.qqjt5xi.mongodb.net/todonext"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_c2Vuc2libGUtd2hhbGUtNC5jbGVyay5hY2NvdW50cy5kZXYk
  CLERK_SECRET_KEY=sk_test_n5UZ8ofoztgONC5CLu3x7ftp0ZjOdBFw56IaALGcK7